### ISSUE TITLE
Sharding stops working post node restart 

### ISSUE THREAD

**Issue by mohanpriyadarshi** [miciek/akka-sharding-example#2]
Sharding stops working  post non seed node restart.Only way to recover the shard is to restart seed node. Any specific setting which handles such scenario?

**Comment by miciek** [comment]
Thanks for contributing to the project :) I will try to reproduce this by killing the non seed node and will get back to you with the answer.

**Comment by miciek** [comment]
@mohanpriyadarshi I tried to reproduce the problem but have not succeeded. What I am doing is:
1. start seed node on port `2551`
2. start non seed node on port `2552`
3. send several requests for different junctions
4. kill non seed node
5. start new non seed node on port `2552` and wait for them to reconnect and stabilise
6. send several requests for different junctions and this works exactly like in `3.`.

Can you elaborate and write the exact scenario? Thanks a lot!
